[phases.install]
cmds = ["...",'test -d ./helper && echo "Directory exists"',"cp -r ./helper/ /app/node_modules/@huggingface/dist"]

[phases.build]
cmds = ["...","echo build","cp -r ./helper/ /app/node_modules/@huggingface/dist"]c