[phases.install]
cmds = ["...","echo build2","ls","cp -r /app/helper/ /app/node_modules/@huggingface/dist"]

[phases.build]
cmds = ["...","echo build","cp -r ./helper/ /app/node_modules/@huggingface/dist"]