[phases.install]
cmds = ["...","echo build2","ls helper","ls node_modules/@huggingface","cp -r ./helper/ ./node_modules/@huggingface/dist"]

[phases.build]
cmds = ["...","echo build","cp -r ./helper/ /app/node_modules/@huggingface/dist"]