[phases.install]
cmds = ["...","test -d ./helper && echo "Directory exists" || echo "Directory does not exist"","cp -r ./helper/ /app/node_modules/@huggingface/dist"]

[phases.build]
cmds = ["...","echo build","cp -r ./helper/ /app/node_modules/@huggingface/dist"]